config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  root to: 'homes#top'
  get 'home/about'=>'homes#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:create, :index, :show, :destroy, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end  
  
  validates :title, presence: true
  validates :body, presence: true, length:{maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  #フォローした側、された側の関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

   validates :name, presence: true, uniqueness: true, length:{minimum: 2, maximum: 20}
   validates :introduction, length:{maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  #フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  #フォローを外した時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  #フォローしているかの判定
  def following?(user)
    followings.include?(user)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  def after_sign_in_path_for(resource)
    flash[:notice] = "successfully"
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "successfully"
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    book_comments = current_user.book_comments.new(book_comment_params)
    book_comments.book_id = @book.id
    book_comments.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment=BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @book_comment.destroy
  end

  private

  def book_comment_params
     params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "successfully"
    redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
   @books = Book.all
   @book = Book.new
   @user = current_user
  end

  def show
   @books = Book.all
   @book = Book.find(params[:id])
   @book_comment = BookComment.new
   @book_comments = @book.id
   @book_new= Book.new
   @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
     redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "successfully"
     redirect_to book_path(@book)
    else
     render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
    
  end  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
 
def search
    @content = params['search']['content']
    @how = params['search']['how']
    @model = params['search']['model']
    @datas = search_for(@how, @model, @content)
end

private

  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'user'
      User.where('name LIKE ?', "#{content}%")
    elsif model == 'book'
      Book.where('title LIKE ?', "#{content}%")
    end
  end

  def backward(model, content)
    if model == 'user'
      User.where('name LIKE ?', "%#{content}")
    elsif model == 'book'
      Book.where('title LIKE ?', "%#{content}")
    end
  end

  def partical(model, content)
    if model == 'user'
      User.where('name LIKE ?', "%#{content}%")
    elsif model == 'book'
      Book.where('title LIKE ?', "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books= @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
     flash[:notice] = "successfully"
     redirect_to user_path(@user)
     else
     render :edit
     end
  end


   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/seraches_helper.rb
module SerachesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
<table>
  <tbody>
    <% book_comments.each do |book_comment| %>
      <tr>
        <td><%= image_tag book_comment.user.get_profile_image(85,85) %></td>
        <td><%= book_comment.comment %></td>
        <% if book_comment.user == current_user %>
          <td><%= link_to "Destroy", book_book_comment_path(book_comment.book.id,book_comment.id), method: :delete, remote: true %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$(".book-comments-index").html("<%= j(render 'book_comments/index', book: @book, book_comments: @book.book_comments) %>");
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$(".book-comments-index").html("<%= j(render 'book_comments/index', book: @book, book_comments: @book.book_comments) %>");

app/views/books/edit.html.erb
<main>
 <div class= "container">
  <div class="row">
   <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
   <% end %>
 <h1>Editing Book</h1>
   <%= form_with model: @book do |f| %>
    <label for="bookTitle">Title</label><br>
    <%= f.text_field :title, autofocus: true, id:"book_title"%><br>
    <label for="bookBody">Opinion</label><br>
    <%= f.text_area :body %><br>
    <%= f.submit "Update Book" %>
    <% end %>
    <%= link_to "Show" ,book_path(@book) %>
     |
    <%= link_to "Back" ,books_path %>
   </div>
   </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
<p id= "notice"></p>
 <div class= "container px-5 px-sm-0">
  <div class= "row">
   <div class= "col-md-3">
    <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
   <% end %>
 <h2>User info</h2>
  <%= image_tag @user.get_profile_image(100,100) %>
  <table class= "table">
   <tbody>
    <tr></tr>
     <tr>
      <th>name</th>
       <th><%=@user.name%></th>
       </tr>
     <tr>
      <th>introduction<%= @user.introduction%></th>
     </tr>
   </tbody>
  </table>
  <div class= "row">
   <div class="col-md-10">
    <div>
    <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog "></i>
    <% end %>
    </div>
   </div>
  </div>
   <h2 class= "mt-3">New book</h2>
   <%= form_with model: @book do |f|%>
    <div class="form-group">
     <label for="book_title">Title</label><br>
     <%= f.text_field :title%>
     </div>
    <div class="form-group">
     <label for="book_opinion">Opinion</label><br>
     <%= f.text_area :body%>
     </div>
     <div class="form-group">
      <%= f.submit'Create Book' %>
     </div>
    <% end %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
    <table class= "table table-hover table-inverse">
     <thead>
     <tr>
       <th>Title</th>
       <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>
    <tbody>
      <% @books.each do | book | %>
       <tr>
        <th><%= link_to user_path(book.user) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %></th>
        <th><%= link_to book_path(book) do %><%=book.title %><% end %></th>
         <th><%=book.body %></th>
          <td id="favorite_buttons_<%= book.id %>">
           <%= render "favorites/favorite", book: book %>
          </td>
         <th><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></th>
        </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>
</main>

app/views/books/show.html.erb
<main>
 <p id= "notice"></p>
  <div class= "container px-5 px-sm-0">
   <div class= "row">
    <div class= "col-md-3">
    <div>
     <%= flash[:notice] %>
    </div>
 <h2>User info</h2>
     <%= image_tag @user.get_profile_image(100,100) %>
     <table class= "table">
      <tbody>
       <tr></tr>
       <tr>
        <th>name</th>
         <th><%=@user.name%></th>
         </tr>
         <tr>
         <th>introduction<%= @user.introduction%></th>
        <th></th>
         </tr>
        <tr>
         <td>follows <%= @user.followings.count %></td>
        </tr>
        <tr></tr>
        <tr>
         <td>followers <%= @user.followers.count %></td>
        </tr>
      </tbody>
     </table>
     <div class="col-md-10">
      <div>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
       </div>
     </div>
     <h2 class= "mt-3">New book</h2>
     <%= form_with model: @book_new do |f|%>
      <div class="form-group">
       <label for="book_title">Title</label><br>
       <%= f.text_field :title%>
       </div>
      <div class="form-group">
       <label for="book_opinion">Opinion</label><br>
       <%= f.text_area :body%>
      </div>
      <div class="form-group">
      <%= f.submit'Create Book' %>
      </div>
      <% end %>
      </div>
    <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
     <table class= "table">
      <tbody>
       <tr>
        <td>
         <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(70,70) %><br>
          <%= @user.name %>
         <% end %>
        </td>
        <td><%= @book.title %></td>
         <td><%= @book.body %></td>
          <td id="favorite_buttons_<%= @book.id %>">
           <%= render "favorites/favorite", book: @book %>
          </td>
          <td>コメント件数：<%= @book.book_comments.count %></td>
         <% if @book.user == current_user %>
           <td><%= link_to "Edit" ,edit_book_path(@book) %></td>
           <td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
         <% end %>
        </tr>
       </tbody>
      </table>
      <div class = "book-comments-index">
        <%= render "book_comments/index", book_comments: @book.book_comments %>
        </div>
        <%= form_with model:[@book, @book_comment], local: false do |f| %>
        <%= f.text_area :comment, :size => "70x4" %><br>
        <%= f.submit "送信" %>
        <% end %>
     </div>
    </div>
   </div>
</main>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
 <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
  ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
  ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<main>
  <div class="container">
   <div class="row">
     <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!! </h1>
     </div>
    </div>
   </div>
</main>

app/views/homes/top.html.erb
<main>
 <p id="notice"></p>
   <div>
   <%= flash[:notice] %>
   </div>
 <div class="container">
  <div class="row">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!! </h1>
    <p> In <i class="fas fa-book"></i> <strong>Bookers</strong> , </p>
    <p> you can share and exchange your opinions , inpressions , and emotions<br></p>
    <p>about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="col-11">
       <div>
       <%= link_to"Log in", new_user_session_path, class: "btn  btn-info btn-outline-secondary btn-sm btn-block text-light mb-3"%>
     </div>
    </div>
      <div class="col-11">
       <div>
       <%= link_to"Sign up", new_user_registration_path, class: "btn btn-success btn-outline-secondary btn-sm btn-block text-light"%>
      </div>
     </div>
    </div>
   </div>
  </div>
 </div>
</main>

app/views/relationships/_list.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table>
     <thead>
      <tr></tr>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        </tr>
      <tr></tr>
      </thead>
      <tbody>
       <tr>
        <td><%= image_tag user.get_profile_image(65, 65)%></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show",user_path(user) %></td>
       </tr>
      </tbody>
    </table>
  <% end %>
    <% else %>
    <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<h1>Follow Users</h1>
<%= render 'list', users: @users %>

app/views/relationships/followings.html.erb
<h1>Follow Users</h1>
<%= render 'list', users: @users %>

app/views/users/edit.html.erb
<main>
 <p id= "notice"></p>
 <div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <% if @user.errors.any? %>
    <%= @user.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
   <% end %>
 <h2>User info</h2>
   <%= form_with model: @user do |f| %>
    <label for="userName">Name</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br>
    <label for="userImage">Image</label><br>
    <%= f.file_field :profile_image, placeholder: "ユーザー画像", accept: "image/*" %><br>
    <label for="userBody">Introduction</label><br>
    <%= f.text_area :introduction%><br>
    <%= f.submit "Update User" %>
   <% end %>
   </div>
  </div>
 </div>
</main>

app/views/users/index.html.erb
<main>
 <p id= "notice"></p>
 <div class= "container px-5 px-sm-0">
   <div class= "row">
    <div class= "col-md-3">
    <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) %>
 <table class= "table">
   <tbody>
    <tr></tr>
     <tr>
      <th>name</th>
       <th><%=@user.name%></th>
       </tr>
     <tr>
       <th>introduction<%= @user.introduction%></th>
       <th></th>
     </tr>
     <tr></tr>
     <tr>
      <td>follows <%= link_to @user.followings.count, user_followings_path(@user.id) %></td>
     </tr>
     <tr></tr>
     <tr>
      <td>followers <%= link_to @user.followers.count, user_followers_path(@user.id) %></td>
     </tr>
   </tbody>
  </table>
  <div class= "row">
   <div class="col-md-10">
    <div>
    <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
    <% end %>
    </div>
   </div>
  </div>
    <h2 class= "mt-3">New book</h2>
     <%= form_with model: @book do |f|%>
      <div class="form-group">
       <label for="book_title">Title</label><br>
       <%= f.text_field :title%>
       </div>
       <div class="form-group">
        <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body%>
        </div>
        <div class="form-group">
       <%= f.submit'Create Book' %>
      <% end %>
     </div>
     </div>
     <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table">
     <thead>
     <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
    </tr>
  </thead>
   <tbody>
    <% @users.each do | user | %>
     <tr>
      <td><%= image_tag user.get_profile_image(65, 65)%></td>
      <td><%= user.name%></td>
      <td>フォロー数: <%= user.followings.count %></td>
      <td>フォロワー数: <%= user.followers.count %></td>
      <td>
       <% if current_user.following?(user) %>
         <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
        <% else %>
         <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
       <% end %>
      </td>
      <td><%= link_to "Show",user_path(user) %></td>
     </tr>
    <% end %>
     </tbody>
    </table>
    </div>
    </div>
   </div>
   </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id= "notice"></p>
   <div class= "container px-5 px-sm-0">
    <div class= "row">
    <div class= "col-md-3">
     <div>
      <%= flash[:notice] %>
     </div>
    <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) %>
 <table class= "table">
   <tbody>
    <tr></tr>
     <tr>
      <th>name</th>
       <th><%=@user.name%></th>
       </tr>
       <tr>
        <th>introduction<%= @user.introduction%></th>
     <th></th> 
       </tr>
     <tr></tr>
       <tr>
        <td>follows <%= link_to @user.followings.count, user_followings_path(@user.id) %></td>
       </tr>
     <tr></tr>
       <tr>
        <td>followers <%= link_to @user.followers.count, user_followers_path(@user.id) %></td>
       </tr>
       <tr>
      <td>
      <% if current_user == @user %>
      <% else %>
      <% if current_user.following?(@user) %>
         <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
        <% else %>
         <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
       <% end %>
      <% end %>
      </td>
     </tr>
   </tbody>
  </table>
  <div class= "row">
   <div class="col-md-10">
    <div>
    <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
    </div>
   </div>
  </div>
   <h2 class= "mt-3">New book</h2>
   <%= form_with model: @book do |f|%>
    <div class="form-group">
     <label for="book_title">Title</label><br>
     <%= f.text_field :title%>
     </div>
    <div class="form-group">
     <label for="book_opinion">Opinion</label><br>
     <%= f.text_area :body%>
     </div>
     <div class="form-group">
     <%= f.submit'Create Book' %>
   </div>
   <% end %>
 </div>
<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
  <table class="table table-hover table-inverse">
   <thead>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
   </tr>
   </thead>
  <tbody>
    <% @books.each do | book | %>
     <tr>
     <th><%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %></th>
     <th><%= link_to book_path(book) do %><%=book.title %><% end %></th>
     <th><%=book.body %></th>
     <th><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></th>
     </tr>
    <% end %>
  </tbody>
  </table>
 </div>
</main>